# .swiftlint.yml
disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - force_unwrapping
function_body_length:
  warning: 200
  error: 300
opt_in_rules:
  - array_init
  - attributes
  - block_based_kvo
  - closure_end_indentation
  - closure_spacing
  - collection_alignment

# Настройки для правил
line_length: 120
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 400
  error: 500
nesting:
  type_level: 3

# Исключения для конкретных файлов и папок
excluded:
  - Pods
  - Carthage
